### ISSUE TITLE
Error in routine gwq_readin.f90 (1):      1st component of qpt_grid must be positive

### ISSUE THREAD

**Issue by mkrompiec** [mmdg-oxford/SternheimerGW#1]
Hello, I am trying to run a GW calculation on InP, starting from a PBE calculation in QE. I am getting the following error:     Error in routine gwq_readin.f90 (1):
     1st component of qpt_grid must be positive
I am using a standard Monkhorst-Pack grid in my SCF calculation In SternheimerGW calculation, I tried both just gamma point and the same grid as in QE but the error persists.

**Comment by martin-schlipf** [comment]
Did you set the qpt_grid variable? If you compare your gw input file to the example file provide for silicon, what changes did you do?

**Comment by mkrompiec** [comment]
Thanks for your quick answer! Indeed I didn't set up the qpt_grid variable, my bad. But now (with the gw.in file exactly the same - apart from the file prefix - as in the Si example) I get another error:
Error in routine ggens (2):
mismatch in number of G-vectors

Turns out it was an MPI-related issue - if anybody else stumbles on this, this is how gw.x should be run in parallel:
mpirun -np $SLURM_NTASKS gw.x -npool $SLURM_NTASKS  < $infile > $outfile

**Comment by mkrompiec** [comment]
This seems to be an MPI-related issue - it runs OK in serial mode.

**Comment by martin-schlipf** [comment]
Number of pools and images need to combine to the total number of CPU. By default Quantum Espresso uses G vector parallelism, which is not implemented for SternheimerGW
mpirun -np X gw.x -npool Y -nimage Z < gw.in > gw.out
with X = Y * Z.

**Comment by mkrompiec** [comment]
Thanks a lot, Martin!

**Comment by uttamphy** [comment]
Dear martin
I have compiled the code and run examples given in code. I found the error
Error in routine ggens (2):
     mismatch in number of G-vectors
I only changed the temp and pseudo dir names in file nothing else.
